### ISSUE TITLE
Remove relative routing

### ISSUE THREAD

**Issue by EECOLOR** [kaliberjs/routing#8]
This library was designed with relative routes as a main priority. Relative routes in combination with a static route map however proves to be problematic.

The static route map proved itself more valuable than relative routes. While relative routes on the surface seem to be more in line with the component model (see motivation in the readme) they are actually hindering portability of components. Having a relative route means the context (parent in the route map) should be correct, tying the child to a specific parent.

Since we don't want to encourage relative routes, we better remove them to simplify the library.

@peeke, @larsvankleef any thoughts?

**Comment by peeke** [comment]
@EECOLOR I agree with removing the relative routes.

I think the component model is not really relevant in the context of routing. You retrieve a blob of data which is tied to a specific route and display using pages to render reusable components. If you have to link relatively, you can always facilitate this on page level, where you know which routes are relative to the current page. This way also you make sure that active thought is put into where you end up, following that link.
